# Generated by Django 2.1.3 on 2018-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180916_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('members', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('github_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('publication', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('github_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('github_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
