# Generated by Django 2.1.3 on 2018-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20181203_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('github_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
    ]
