# Generated by Django 2.1.3 on 2018-12-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20181203_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='members',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='members',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='members',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
    ]
