# Generated by Django 2.1.2 on 2018-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.CharField(max_length=20),
        ),
    ]
