# Generated by Django 2.1.4 on 2018-12-10 08:49

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20181209_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='description',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
